### ISSUE TITLE
Mentee Cannot Create Events

### ISSUE THREAD

**Issue by Alnattar** [Z701-1/PMUMentor#2]
The createEvent() method in the Mentee class throws a NullPointerException when called.

**Comment by Z701-1** [comment]
Fixed

The cause was the createEvent() method in the Mentee class did not validate the eventDetails parameter, causing a NullPointerException when null or empty value were passed.

I added a validation step in the createEvent() method to check for null or empty strings before moving forward. If the input is invalid, the method will give out an error message and exit.
